### ISSUE TITLE
New Name for probe-screen

### ISSUE THREAD

**Issue by freisei** [linuxcnc-probe-screen/probe-screen-ng#1]
I suggest a new name for this version of probe-screen.

It´s hard to find for users what is the correct/newest version to use. 

"Probe-Screen" was the first name of verser-git´s Initial-Release, verser´s newer screen (base of this fork) is called Probe-Screen-V2. So i think its bad when the newest version has a name that suggests, it is older than its own base.

My idea is simply "probe-screen-v3.0"

**Comment by kiall** [comment]
I'd be against `probe-screen-v3` for 2 reasons .. 1) it's suggesting it's somehow the official successor of probe-screen-v2 - and I don't think this is that... and 2) One day @verser-git might release a v3 of their own, which will just lead to confusion all around.

I'm hopeful enough people have forgotten about the original "probe-screen" repo that the generic name can be kept :smile: But an alternative is fine - I just don't like the idea of calling it v3 :)

**Comment by freisei** [comment]
ok, this are good reasons to be against this name.
I think "probe-screen" should stay in the name, because it´s based on it and to give tribute to verser.

What about
- "probe-screen-ng" (next generation)
- "probe-screen-plus"
- "JAPS" "just-anonther-probe-screen"
- "pswain" "probe screen without any good name"

any better idea?

**Comment by kiall** [comment]
I'd vote for "probe-screen-ng" from that list :) I'll rename the repo later today!

**Comment by kiall** [comment]
Renamed to https://github.com/linuxcnc-probe-screen/probe-screen-ng :)
