### ISSUE TITLE
Come back with G1 vs G0

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#16]
https://github.com/linuxcnc-probe-screen/probe-screen-ng/blob/98d745ccfe5731d8c0080fd1cc9c231cfa135171/macros/psng_gotots.ngc#L4

Hi

I agree with you for the use of G0 but in some macro this is G1 that is used, i do not want to force to use G1 !!

If you want G0 some other macro need to be edited. 

br

**Comment by alkabal** [comment]
I think better than using G0 we can expose 3 value 

RAPID_SPEED = like G0 move
PROBE_RAPID = fast probe move
PROBE_SLOW = last very slow move


Br

**Comment by alkabal** [comment]
well at the end this is already done like this but with 2 value from spinbox GUI

So at the end proposition is more close to : 
FAST_SPEED = for going to toolchange position and toolsetter position before probing
RAPID_SPEED = like actually for  move during probing

this is more or less the actual behavior excepted probe_down and gotos use G1 for preliminary positioning vs G0 in manual_toolchange.

**Comment by kiall** [comment]
> I think better than using G0 we can expose 3 value
> 
> RAPID_SPEED = like G0 move
> PROBE_RAPID = fast probe move
> PROBE_SLOW = last very slow move
> 
> Br

So, we already have 2 of these in the UI - PROBE_RAPID (aka Search Velocity) and PROBE_SLOW (aka Probe Velocity). We might not be consistently using these values though. We should be, if we're not.

These two are obviously within the scope of a probe screen. G0 or G1 speeds simply don't make sense to use for these.

After those two, there are 2 additional speeds to care about:

1) Moving to to/from the tool change and tool setter locations. IMO, this should just be a G0 move. What specific reason makes you want to replace G0 with a custom variable? For me, the tool change location and tool setter locations are on opposite sides of the bed (front and back) - so anything that slows this down unnecessarily would really bother me, and add a not insignificant amount of excess cycle time.

2) Moving around during a probe. For example, when doing an X+Y- outside corner measurement, a move is done from the X probe location to the Y probe location. This is what the RAPID_SPEED ini variable is (mostly) used for. Again, normal G0 doesn't really make sense here, the probe is far too close to the work-piece to move that fast.


So - For me, that leaves us with 4 distinct feed rates:

1) Search Velocity (in the UI)
2) Probe Velocity (in the UI)
3) G0 for moving between different locations
4) G1 with the INI "RAPID SPEED" setting for smaller moves while the probe is close to the workpiece

(the INI "RAPID SPEED" setting needs a better name, it's confusing and makes it sound like it's somehow related to G0 - while it's not actually related to G0, or the G0 speeds, at all)

**Comment by alkabal** [comment]
Well about G0 i understand, i need to retry : in reality i have corrected my velocity settings because i found a issue with gear scale and maybe this is why i dislike the G0 because at first is too much fast but maybee is correct now.

But in all way in my opinion using G1 with a separate setting for speed allow user to set the max supported speed like G0 or what is wanted.


I agree with renaming the RAPID_SPEED. they are other things that need to be renamed for stop possible confusion (i see you have renamed some macro : perfect thank you)
Br
