### ISSUE TITLE
Save and restore modal states in a consistent manor

### ISSUE THREAD

**Issue by kiall** [linuxcnc-probe-screen/probe-screen-ng#21]
A probe screen like this one just can't use `M72` or `M73` to restore modal states, so the various macros and python are sometimes, but not always, restoring modal states correctly when they finish.

At the start of each macro, we should save all modal states. At the end of each macro (including at error points, or early returns) we must restore the modal states which we haven't explicitly intended to change (e.g. TLOs)

To do this, we have a few options.

1) We can add "modal_save" and "modal_restore" macros which use named global parameters to save and restore all modal state. This is the simplest method, and adds the least code to each of the other macros. However, if a macro calls into another macro, we will loose the original saved state.

2) We can add "modal_save" and "modal_restore" macros which use named local parameters to save and restore all modal state. This could add a lot of code to each of the other macros, but would allow for nested macro calls to work correctly.

3) We can manually use named local parameters to store modal states, and manually restore those states when we leave a macro - this will add even more code than option 2 to the other macros, and would easily get out of sync between the different macros.

I'm not sure which option is ideal... I'll look into seeing if there is a way to make option 1 work with nested macro calls.

A list of modal states can be found here: http://linuxcnc.org/docs/html/gcode/m-code.html#mcode:m70

**Comment by alkabal** [comment]
[restore_mill.txt](https://github.com/linuxcnc-probe-screen/probe-screen-ng/files/5702448/restore_mill.txt)


Hi here is my attempt for add this in some macro

#<metric> = #<_metric>
#<absolute> = #<_absolute>
#<feed> = #<_feed>
#<ccomp> = #<_ccomp>
#<tool_offset> = #<_tool_offset>
#<coord_system> = #<_coord_system>
#<ijk_absolute_mode> = #<_ijk_absolute_mode>

; restore g20/21, g90/g91, feedrate cuter-comp
	o<restore_mill> call [#<metric>] [#<absolute>] [#<feed>] [#<ccomp>] [#<tool_offset>] [#<coord_system>] [#<ijk_absolute_mode>]

**Comment by alkabal** [comment]
`
#<metric> = #<_metric>
#<absolute> = #<_absolute>
#<feed> = #<_feed>
#<ccomp> = #<_ccomp>
#<tool_offset> = #<_tool_offset>
#<coord_system> = #<_coord_system>
#<ijk_absolute_mode> = #<_ijk_absolute_mode>`

**Comment by alkabal** [comment]
[go-machine-home-mill.txt](https://github.com/linuxcnc-probe-screen/probe-screen-ng/files/5702460/go-machine-home-mill.txt)


more easy to read in a file

**Comment by kiall** [comment]
Use three backticks (`) around code to get it to format correctly! I edited your comment above to add them as an example.

Yea, that's along the lines of what I'm thinking. It adds lots of code though, so I'm hoping to find something that's harder to get out of sync - e.g. if we need to save/restore a new state, should we have to update the 100 or so locations `o<restore_state>` is called from? I'd ideally prefer not to need to!

**Comment by kiall** [comment]
> [restore_mill.txt](https://github.com/linuxcnc-probe-screen/probe-screen-ng/files/5702448/restore_mill.txt)
> 
> Hi here is my attempt for add this in some macro
> 
> ```
> #<metric> = #<_metric>
> #<absolute> = #<_absolute>
> #<feed> = #<_feed>
> #<ccomp> = #<_ccomp>
> #<tool_offset> = #<_tool_offset>
> #<coord_system> = #<_coord_system>
> #<ijk_absolute_mode> = #<_ijk_absolute_mode>
> 
> ; restore g20/21, g90/g91, feedrate cuter-comp
> o<restore_mill> call [#<metric>] [#<absolute>] [#<feed>] [#<ccomp>] [#<tool_offset>] [#<coord_system>] [#<ijk_absolute_mode>]
> ```

Also, you're passing tool-offset in as parameter 5, but the macro is expecting coordinate system as param 5. It's this kind of stuff I'm hoping to be able to avoid :) manually lining up params in 100s of places is bound to end up with some mistakes!

**Comment by alkabal** [comment]
I don't understand where you see : tool-offset in as parameter 5, but the macro is expecting coordinate system as param 5

**Comment by kiall** [comment]
```
o<restore_mill> call [#<metric>] [#<absolute>] [#<feed>] [#<ccomp>] [#<tool_offset>] [#<coord_system>] [#<ijk_absolute_mode>]
                          1            2           3          4           5^
```

then, inside the macro, you have:

```
o500 if [#5 NE #<_tool_offset>]
```

It's an easy mistake to make, hopefully one we can avoid by not having to manually save everything to vars and manually pass all of those back into the restore function. I'm not sure that's possible, but I'll spend some time looking :)

**Comment by kiall** [comment]
Replacing my last comment - I seem to be mistaken looking at the code again. I'm nearly sure I saw that? Could you have updated the file in the meantime? :D

**Comment by alkabal** [comment]
no lool

**Comment by kiall** [comment]
![Screenshot_20201216-125039](https://user-images.githubusercontent.com/52713/102350817-68775b00-3f9d-11eb-90de-e563248cc4a1.png)

It was still open on my phone - #5 was clearly referencing coordinate system ¯\_(ツ)_/¯

**Comment by alkabal** [comment]
I appologize your right at start editing this file for add G43 i have save without full change.

I did not remenber sorry, and i does not see edited for the message, realy sorry

**Comment by kiall** [comment]
> I appologize your right at start editing this file for add G43 i have save without full change.
> 
> I did not remenber sorry, and i does not see edited for the message, realy sorry

Hah - no problem. Just glad I'm not going insane :D

**Comment by alkabal** [comment]
and i know that for me i have some memories trouble...
