### ISSUE TITLE
Python code try to understand self.stat.poll() 

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#22]
Hi

I have some trouble understanding why we cand found some self.stat.poll() at "random location"in the code 

https://github.com/alkabal/probe-screen-ng/blob/cdefdd972b8190ea32e79fa26d33cb983c739ba9/psng/psng.py#L249
https://github.com/alkabal/probe-screen-ng/blob/cdefdd972b8190ea32e79fa26d33cb983c739ba9/psng/psng.py#L288
https://github.com/alkabal/probe-screen-ng/blob/cdefdd972b8190ea32e79fa26d33cb983c739ba9/psng/psng.py#L318
https://github.com/alkabal/probe-screen-ng/blob/cdefdd972b8190ea32e79fa26d33cb983c739ba9/psng/psng.py#L1770
https://github.com/alkabal/probe-screen-ng/blob/cdefdd972b8190ea32e79fa26d33cb983c739ba9/psng/psng.py#L1847
https://github.com/alkabal/probe-screen-ng/blob/cdefdd972b8190ea32e79fa26d33cb983c739ba9/psng/psng.py#L1923
https://github.com/alkabal/probe-screen-ng/blob/cdefdd972b8190ea32e79fa26d33cb983c739ba9/psng/psng.py#L1999

br

**Comment by kiall** [comment]
It's polling for the latest machine status prior to reading that status - it's documented here: http://linuxcnc.org/docs/html/config/python-interface.html

**Comment by alkabal** [comment]
But why we can't have this after all  def on_xxxxxxxxxxxxxxx ?

For me poor undertanding this is somem "random location"
