### ISSUE TITLE
Problem using MSG in hook macro

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#28]
Hi

I have many problem using M0 in hook macro

the logic for ocode routine did not manage this correctly and i big trouble understanding what i need to do for deal with that.

So for now i experiment to call hook from python code with special routine that work partialy.
 without regarding other change can i ask what did you think about that ?

    def ohookcode(self, s, data=None):
        self.command.mdi(s)
        self.stat.poll()
        #self.command.wait_complete()
        print("ohook_start = %s" % self.stat.interp_state)
        while self.stat.interp_state != linuxcnc.INTERP_PAUSED:
            print("ohook_loop1 = %s" % self.stat.interp_state)
            self.command.wait_complete()
            self.stat.poll()

        while self.stat.interp_state != linuxcnc.INTERP_IDLE:
            print("ohook_loop2 = %s" % self.stat.interp_state)
            self.command.wait_complete()
            self.stat.poll()      

        self.command.wait_complete()
        print("ohook_end = %s" % self.stat.interp_state)
        return 0`

`

Br

edit at the end this one work enough  : 
```
    def ohookcode(self, s, data=None):
        self.command.mdi(s)
        self.stat.poll()
        print("ohook_start = %s" % self.stat.interp_state)
        print("ohook_start_queue = %s" % self.stat.queue)

        while self.stat.interp_state != linuxcnc.INTERP_IDLE:
            print("ohook_loop2 = %s" % self.stat.interp_state)
            print("ohook_loop2_queue = %s" % self.stat.queue)
            self.command.wait_complete()
            self.stat.poll()
            
        self.command.wait_complete()            
        print("ohook_end = %s" % self.stat.interp_state)
        print("ohook_end_queue = %s" % self.stat.queue)
        return 0
```

But the problem is next call with regular macro using ocode routine ended with some NML error

**Comment by alkabal** [comment]
I think also the original ocode routine did not like call other macro from other

**Comment by kiall** [comment]
> Hi
> 
> I have many problem using M0 in hook macro
> 
> the logic for ocode routine did not manage this correctly and i big trouble understanding what i need to do for deal with that.

If there an specific error message or issue you can describe? Does this happen with a hook macro that only has a M0 and nothing else in it?

I'll give it a go tomorrow and see if I can spot the issue either way .. 

> But the problem is next call with regular macro using ocode routine ended with some NML error

Can you provide the error message?

**Comment by alkabal** [comment]
Unfortunately i find only error 11 but i'm unsure about that

I get only some user probe error and program fail or in other situation pause is not respected.

It's (for me) difficult to understand what append but playing with hook or other subcall seem to be unliked by ocode routine, i have passed many many hours trying to figure what is needed to do for workaround without understanding. (you have see i'm not expert)

i try to clean my first revision and send to my fork this night and maybe tomorrow i will retry with yesterday attempt (call hook from pyhton)

Thanks

**Comment by alkabal** [comment]
other things important : 

using remap m6 work like a charm because psng_manual_change.ngc is managed by the remap process and is not call by python

**Comment by alkabal** [comment]
if you check my fork i suggest to not read without checking by commit change but read this as other source. (if you know the actual code i hope this is "easy" to understand what i have done)

**Comment by alkabal** [comment]
```
########### REMOVED if self.error_poll() == -1: DOES NOT WORK WITH HOOK
    def ocode(self, s, data=None):
        self.command.mdi(s)
        self.stat.poll()
        while self.stat.interp_state != linuxcnc.INTERP_IDLE:
            if self.error_poll() == -1:
                print("interp_err_status = %s" % self.stat.interp_state)
                print("interp_err_queue = %s" % self.stat.queue)
                print("interp_err_operator = %s" % linuxcnc.OPERATOR_ERROR)
                print("interp_err_nml = %s" % linuxcnc.NML_ERROR)
                e = linuxcnc.error_channel()
                error = e.poll()
                kind, text = error
                if kind in (linuxcnc.NML_ERROR, linuxcnc.OPERATOR_ERROR):
                    typus = "error"
                else:
                    typus = "info"
                print typus, text  
                return -1
            self.command.wait_complete()
            self.stat.poll()
        self.command.wait_complete()
        if self.error_poll() == -1:
            print("interp_err2_status = %s" % self.stat.interp_state)
            print("interp_err2_queue = %s" % self.stat.queue)
            print("interp_err2_operator = %s" % linuxcnc.OPERATOR_ERROR)
            print("interp_err2_nml = %s" % linuxcnc.NML_ERROR)
            return -1
        return 0
############ REMOVED if self.error_poll() == -1: DOES NOT WORK WITH HOOK
```

Using this i found ;

                interp_err_status = 2
                iinterp_err_queue = 0
                interp_err_operator =11
                interp_err_nml = 1

kind, text = error
TypeError: 'NoneType' object is not iterable



Ps : too late for this night and i have already try without success but it can be better to ask, did you think using `oxxx return` can do something different vs `o<psng_hook> endsub` ?

**Comment by kiall** [comment]
Hey @alkabal - I tried this out this morning, calling M0/M1 within the hook macro works just fine. I added this macro to my install, and executed the `psng_probe_workpiece` macro via the UI (which in turn triggers the macro via Python). Both M codes worked as expected + the machine paused after each.

I suspect one of the other changes in your fork, or something else in your hook macro, is causing the issue.

> if you check my fork i suggest to not read without checking by commit change but read this as other source. (if you know the actual code i hope this is "easy" to understand what i have done)

![Screenshot from 2020-12-22 09-02-33](https://user-images.githubusercontent.com/52713/102870123-7eb96700-4434-11eb-9c98-f4e93c4014c9.png)

Honestly, I don't have the time to review a changeset this large - can you create a forked branch with a minimal set of changes necessary to demonstrate the issue?

```
$ cat macros/psng_hook.ngc 
o<psng_hook> sub

(MSG, Calling M0)
M0

(MSG, Calling M1)
M1

(MSG, Done)

o<psng_hook> endsub
M2
```

**Comment by kiall** [comment]
> Honestly, I don't have the time to review a changeset this large - can you create a forked branch with a minimal set of changes necessary to demonstrate the issue?

Also, to be clear - I absolutely appreciate any help etc with making the probe screen better - I really do!

It's just that, with that many changes, it's impossible to tell what's an issue *somewhere* in those changes, and what's an issue with the code in this repo.

Collaboration on Open Source is far easier if small + single purpose changes are made 1 at a time and submitted as Pull Requests. This allows things to be reviewed and merged and the project gets better for everyone :) It's slower, but it also means you're not off on own!

**Comment by alkabal** [comment]
Thanks for reply, test and suggestion i will try soon ! 

> It's just that, with that many changes, it's impossible to tell what's an issue somewhere in those changes, and what's an issue with the code in this repo.

**Comment by alkabal** [comment]
Haha 

I did not remember but the major change i have do is : 

original do not work fine : 
```
        if self.ocode("o<psng_down> call") == -1:
            return

```

original work fine : 
```
        self.command.mdi("o<psng_probe_workpiece> call")
        self.stat.poll()
        while self.stat.interp_state != linuxcnc.INTERP_IDLE:
            self.command.wait_complete()
            self.stat.poll()
        self.command.wait_complete()
```

modified to this does not work fine : 
```

        if self.ocode("o<psng_probe_workpiece> call") == -1:
            return
```

Well did you understand why this i done like that ? 90% use if self.ocode("o< and some other use direct while in the function ?

What did you think about that is greatly wanted lol.

Br

**Comment by alkabal** [comment]
using only my hook without any change

**Comment by alkabal** [comment]
please try to us down with your own macro

**Comment by alkabal** [comment]
From my attempt the system fail after call M0 with your own using psng_down

**Comment by kiall** [comment]
Ah, okay. Using my hook code, and probe down instead of probe workpiece, I can see the issue.

Remove all the (MSG,) lines, and it works just fine. 

The bug is in the .axisrc file - info messages are causing the error pin to be set to true.

**Comment by alkabal** [comment]
oh oh oh

**Comment by alkabal** [comment]
I think i will never found this without help ! many thanks 

Now need to found what is best to do for deal with that

**Comment by alkabal** [comment]
I think i never get any error message from axisrc with the code provided.

never get messagelike this topic
https://162.243.45.186/49-basic-configuration/29187-work-with-probe?start=260#133566
[axisrc.txt](https://github.com/linuxcnc-probe-screen/probe-screen-ng/files/5731350/axisrc.txt)

**Comment by alkabal** [comment]
i get error only from terminal using 
[PYTHON]
PATH_PREPEND = ./python
TOPLEVEL = python/toplevel.py
LOG_LEVEL = 5

**Comment by kiall** [comment]
I'm not sure I understand? What error specifically? If it's the "probe already active" message, then that's pretty much entirely internal to LinuxCNC, and most likely not an issue with the probe screen.

If it's something else, can you include the actual error message?

**Comment by alkabal** [comment]
i have many time view the  "probe already active" but never in a popup style like i can see on the forum.
![F0DD24AC-2F42-4A49-B731-3B11C45A50EB](https://user-images.githubusercontent.com/33371787/102923926-e3a2aa80-4490-11eb-9393-6fa64197edd4.jpg)

**Comment by alkabal** [comment]
Well i think i have understand what append with popup
Imo this version does not display any popup but display in the white log box inside the probe_screen... 

I run from cmdline (without root_window.attributes('-fullscreen', True)) for debugging this dialog-box is outside range with my screen resolution 1920 x 1080 

I have noticed they display nothing if you use LOG_LEVEL = 5

So at the end i think they are no problem with the error display function.

**Only is needed to deal with error management and hook MSG**

**Comment by kiall** [comment]
This should now be fixed by https://github.com/linuxcnc-probe-screen/probe-screen-ng/pull/29

**Comment by kiall** [comment]
> Well i think i have understand what append with popup
> Imo this version does not display any popup but display in the white log box inside the probe_screen...

It's a race condition. Sometimes it'll show as a popup, sometimes it will show in the text box. If you hold the probe down, and then hit the probe down button over+over - you'll see the popup eventually (and a generic error in the text box). For me, it tool 5 tries in a row for the popup to show instead of textbox log entry.
