### ISSUE TITLE
Rework error handling to avoid race conditions with AXIS UI

### ISSUE THREAD

**Issue by kiall** [linuxcnc-probe-screen/probe-screen-ng#30]
Both AXIS UI and the Probe Screen poll for errors. We have no way to guarantee which of the 2 will win the race and receive the error.

There is some hacky code in .axisrc to help ensure the probe screen will always know of an error (though, when AXIS UI wins the race, the error details are gone and all we know is an error has occurred).

The code in PR #29 has some comments explaining this in more detail.

**Comment by alkabal** [comment]
Hi

Many thanks for that ! i will try soon

**Comment by alkabal** [comment]
Hi

Unfortunatly i can't continu trying for now but imo this does not work really better 

saad but thanks for trying

**Comment by kiall** [comment]
I presume you're talking about the changes in https://github.com/linuxcnc-probe-screen/probe-screen-ng/pull/29 ? 

This issue is about some additional / future fixes that are needed to remove some race conditions in the code that means *sometimes* you get a popup with errors, other times you don't and the errors are just logged to the history box on the probe screen.

Anyway - The code in #29 fixes the issue with using `(MSG, ...)` in a macro - if there are other issues, please open a issue for those specific issues :)

**Comment by alkabal** [comment]
https://github.com/linuxcnc-probe-screen/probe-screen-ng/pull/42
