### ISSUE TITLE
suggestion remove psng_postgui.hal

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#4]
Hi

First, thanks for this fork and the work for update !

I have one question why do you keep the use of psng.hal and psng_postgui.hal ?

For what i have try put the line that is alone in postgui inside psng.hal fork fine.

Br

**Comment by freisei** [comment]
I don´t know exactly but i think initially it was because of

```
#unlinkp iocontrol.0.tool-change
#unlinkp iocontrol.0.tool-changed

```
I think we should remove that file and add its content to psng.hal

**Comment by kiall** [comment]
Those those lines aren't necessary, and if you uncomment them, will cause the issue lots of people have with the probe screen just hanging (there's hundreds of reports of this in the probe screen thread on the linuxcnc forums).

We should just remove those lines entirely IMO :)

**Comment by freisei** [comment]
done in branch files_cleanup
