### ISSUE TITLE
Pyth

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#5]
Hi

For launching panel it seem to be enough to use : (the actual info in install_add_to_your.ini are not updated)

EMBED_TAB_COMMAND=gladevcp -x {XID} -u python/psng.py -H probe_icons/psng.hal probe_icons/psng.glade 

psng.py is not in the python folder

br

**Comment by alkabal** [comment]
Another suggestion, put the new branch as default branch.

Thanks for all

**Comment by alkabal** [comment]
Renaming the macro do a lot off trouble regarding to psng.py

**Comment by freisei** [comment]
Hi alkabal!

First thanks for your good input!

Indeed i forget to update the install_add_to_your.ini. I don´t know why @verser did add "halcmd loadusr -Wn gladevcp" i think its a double double. Removing works for me.

I want to keep the psng.py in the psng-folder to keep updates for other users easy in future. It works for me. Do you see any other reason not to do that?

By the way: i am new to git, so i have some trouble with it. Finally i got the modified macro-files to be pushed.

Thanks again.
Greets Freisei

**Comment by kiall** [comment]
I think this is all done & merged as part of #7?

Please reopen or file a new issue if something was missed! :)
