### ISSUE TITLE
Replace G38.4

### ISSUE THREAD

**Issue by alkabal** [linuxcnc-probe-screen/probe-screen-ng#6]
Hi again

Please change inside this file line 49 because G38.4 can cause some trouble.

```
G38.2 Z #<_ini[TOOLSENSOR]MAXPROBE>
G38.4 Z2
G0 Z0.5
; This is commented out only for sim.
F #<_hal[probe.ps_probevel]>
G38.2 Z-3
```
to

```
G38.2 Z#<_ini[TOOLSENSOR]MAXPROBE>
G1 F#<_ini[TOOLSENSOR]RAPID_SPEED> Z2
; This is commented out only for sim.
F #<_hal[probe.ps_probevel]>
G38.2 Z-3
```

**Comment by alkabal** [comment]
line 63 add

`
G53 G0 X[#<_ini[CHANGE_POSITION]X>] Y[#<_ini[CHANGE_POSITION]Y>]`

**Comment by alkabal** [comment]
```
; manual toolchange with automatic tool length probe 

o<manual_change> sub
;(debug, in change tool_in_spindle=#<tool_in_spindle> current_pocket=#<current_pocket>)
;(debug, selected_tool=#<selected_tool> selected_pocket=#<selected_pocket>)

;otherwise after the M6 this information is gone!
#<tool> = #<selected_tool>
#<pocket> = #<selected_pocket>



; we must execute this only in the milltask interpreter
; or preview will break, so test for '#<_task>' which is 1 for 
; the milltask interpreter and 0 in the UI's
O100 if [#<_task> EQ 0]
        (debug, Task ist Null)
O100     return [999]
O100 endif

;first go up
G90
F#<_ini[TOOLSENSOR]RAPID_SPEED>
G53 G1 Z[#<_ini[AXIS_Z]MAX_LIMIT>-1]
; then move to change position
G53 G1 X[#<_ini[CHANGE_POSITION]X>] Y[#<_ini[CHANGE_POSITION]Y>]
G53 G1 Z[#<_ini[CHANGE_POSITION]Z>]

; cancel tool offset
G49

; using the code being remapped here means 'use builtin behaviour'
M6

O200 if [#<_hal[probe.use_toolmeasurement]> EQ 0]
O200 return [3] ; indicate no tool measurement 
O200 endif

G53 G1 X[#<_ini[TOOLSENSOR]X>] Y[#<_ini[TOOLSENSOR]Y>]
G53 G1 Z[#<_ini[TOOLSENSOR]Z>]

O300 if [#<_hal[probe.ps_searchvel]> LE 0]
O300 return [-1] ; indicate searchvel <= 0 
O300 endif

O400 if [#<_hal[probe.ps_probevel]> LE 0]
O400 return [-2] ; indicate probevel <= 0 
O400 endif

F #<_hal[probe.ps_searchvel]>
G91
G38.2 Z#<_ini[TOOLSENSOR]MAXPROBE>
G1 F#<_ini[TOOLSENSOR]RAPID_SPEED> Z2
F #<_hal[probe.ps_probevel]>
G38.2 Z-2

O500 if [#5070 EQ 0]
G90
O500 return [-3] ; indicate probe contact failure to epilog
O500 endif

G90
F#<_ini[TOOLSENSOR]RAPID_SPEED>
G53 G1 Z[#<_ini[CHANGE_POSITION]Z>]
G53 G1 X[#<_ini[CHANGE_POSITION]X>] Y[#<_ini[CHANGE_POSITION]Y>]

#<touch_result> = #5063
#<probeheight> = #<_hal[probe.probeheight]> 
#<blockheight> = #<_hal[probe.blockheight]>

;(DEBUG, #<touch_result>  #<probeheight>  #<blockheight>)

G10 L1 P#<tool> Z[#<touch_result> - #<_hal[probe.probeheight]> + #<_hal[probe.blockheight]>]
G43

;G10 L1 P#<tool> Z#<touch_result>
;G10 L2 P0 Z[#<workpieceheight> + #<probeheight> + #<touch_result>]

; signal success be returning a value > 0:
o<manual_change> endsub [1]
m2


```

**Comment by alkabal** [comment]
In install_add_to_your.ini


REMAP=M6   modalgroup=6  prolog=change_prolog   ngc=manual_change  epilog=change_epilog

to 

REMAP=M6   modalgroup=6  prolog=change_prolog   ngc=psng_manual_change  epilog=change_epilog

**Comment by freisei** [comment]
Hi alkabal,

can you please do speparate issues for each request? I can´t do "closes" on comments.
Thanks.

**Comment by freisei** [comment]
> 
> 
> In install_add_to_your.ini
> 
> REMAP=M6 modalgroup=6 prolog=change_prolog ngc=manual_change epilog=change_epilog
> 
> to
> 
> REMAP=M6 modalgroup=6 prolog=change_prolog ngc=psng_manual_change epilog=change_epilog

is already done but was not commited. (my git trouble)

**Comment by freisei** [comment]
I my config i had some trouble with the fixed Z for going back.
G38.4 makes trouble if the workpiece is spring back because the probe is shortly released and then closed again. Maybe we should take both togeher. Go back by G38.4 and then add some Z for spring back, with is configurable in ini.
maybe
 [TOOLSENSOR]PROBE_Z_LATCH

**Comment by kiall** [comment]
I had similar issues using a hardcoded retract value - hence why I swapped it for a negative probe.

What specific issues does this cause you @alkabal?

**Comment by kiall** [comment]
> I my config i had some trouble with the fixed Z for going back.
> G38.4 makes trouble if the workpiece is spring back because the probe is shortly released and then closed again. Maybe we should take both togeher. Go back by G38.4 and then add some Z for spring back, with is configurable in ini.
> maybe
> [TOOLSENSOR]PROBE_Z_LATCH

We're actually doing (part of) this already - we G38.4 to move off the workpiece, and then retract a further 0.5mm - we can make this extra distance configurable I guess?

**Comment by freisei** [comment]
we even can make configurable to use G38.4
so we have
[TOOLSENSOR]PROBE_Z_RETREAT_WITH_G38.4
[TOOLSENSOR]PROBE_Z_LATCH

If the user have trouble with G38.4 he can decide to rise PROBE_Z_LATCH and set PROBE_Z_RETREAT_WITH_G38.4 to 0

**Comment by kiall** [comment]
> [TOOLSENSOR]PROBE_Z_RETREAT_WITH_G38.4

I'd personally rather avoid this - because it now means theres 2 different code paths to maintain and test and get bug reports for :)

It seems to me that a probe screen should be able to use LinuxCNC's probe G-codes without issue - otherwise, what's the point? :D Lets see what specific issues were had with it before making any changes :)

**Comment by freisei** [comment]
>  theres 2 different code paths to maintain and test and get bug reports for :)
you mean we need different macros? I dont think so.
But ok, for now it would be enough to make PROBE_Z_LATCH configurable.

**Comment by kiall** [comment]
> you mean we need different macros? I dont think so.

No, a single macro can do it... but the specific g-codes used within that macro will change depending on the config. Sometimes, G38.4 will be used, other times G1 Z2 will be used.

This could have a knock on effect to the rest of the macro / code as the Z position you end up in will change depending on which method you use - now we'll have to keep testing both options anytime a chance is made to the macro to be sure it's still going to work :)

(Yes, it's only a small amount of work - but it's usually best to keep things as simple as possible because every extra thing to test makes it harder to keep working - and they all add up :))

**Comment by alkabal** [comment]
Hi

This is not really issue i'm unsure but when i try this i have a message that says probe already triggered or something like that.

**Comment by alkabal** [comment]
About G38.4 i think this can be good but maybee i need to do more test with this one but for now i dislike it lool.

All other macro file do not use G38.4 so this is for me better to use the same logic in all files

**Comment by alkabal** [comment]
In the complete copy of the file https://github.com/linuxcnc-probe-screen/probe-screen-ng/issues/6#issuecomment-740258610

i have also replace G0 with G1 using F#<_ini[TOOLSENSOR]RAPID_SPEED>

**Comment by kiall** [comment]
Maybe the `G0 Z0.5` right after the G38.4 isn't enough in your case? we could try making that larger (say, 1-2mm instead of 0.5mm) and make that number configurable?

> All other macro file do not use G38.4 so this is for me better to use the same logic in all files

Agreed - we should use the same logic everywhere, though I think we should update everything to use G38.4 rather than a fixed distance :)

**Comment by alkabal** [comment]
I think the G38.4 was not executed when i try the standard code

Yes you are right i have see some missing configurable things like this that can be better with config in ini file.

**Comment by alkabal** [comment]
I need to do some test but from yesterday i have a problem with https://github.com/linuxcnc-probe-screen/probe-screen-ng/blob/36671e46f3b9028bce450fe1cbb768b1202baa12/psng/psng.py#L2011

AttributeError: 'NoneType' object has no attribute 'set_filename'

**Comment by freisei** [comment]
With G38.4 the problem can be that 

- the probe is leaving the sensor
- then motion stops
- if for any reason (i.e. the workpiece is sping back a minimum amount or the PID for Z overshoots, or cheap probe) the probe is touching again, before the next G38.2 (OR maybe even the Z-latch) command is executed, linuxcnc stops with an error. Maybe we can prevent/workaround linuxcnc to stop?

**Comment by alkabal** [comment]
i think yes if i remenber the problem was the probe is already leaving the sensor before start G38.4 taht cause the trouble for me.

I have do test with other macro used with my cheap modified Chinese edge finder modified as cheap lathe tool setter...

**Comment by freisei** [comment]
> 
> 
> I need to do some test but from yesterday i have a problem with
> 
> https://github.com/linuxcnc-probe-screen/probe-screen-ng/blob/36671e46f3b9028bce450fe1cbb768b1202baa12/psng/psng.py#L2011
> 
> AttributeError: 'NoneType' object has no attribute 'set_filename'

i think there must be another error or warning messages before that, when you start linuxcnc from command-line.

**Comment by alkabal** [comment]
> > I need to do some test but from yesterday i have a problem with
> > https://github.com/linuxcnc-probe-screen/probe-screen-ng/blob/36671e46f3b9028bce450fe1cbb768b1202baa12/psng/psng.py#L2011
> > 
> > AttributeError: 'NoneType' object has no attribute 'set_filename'
> 
> i think there must be another error or warning messages before that, when you start linuxcnc from command-line.

Hi

I have found the issue, editing the panel with glade for better fitting to my screen glade have removed this parts

`                        <child>
                          <object class="ToolEdit" id="tooledit1">
                            <property name="width_request">100</property>
                            <property name="height_request">30</property>
                            <property name="sensitive">False</property>
                            <property name="can_focus">False</property>
                          </object>
                          <packing>
                            <property name="x">300</property>
                            <property name="y">5</property>
                          </packing>
                        </child>`

So now i can restart to do some test
